// favicon: SVG source (fixture) and raster source (a wide PNG logo with transparent edges).
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import { favicon } from '../src/favicon.js';

const results = [];
const expect = (name, ok) => {
  results.push(ok);
  console.log(`${ok ? '✓' : '✗'} ${name}`);
};
const site = { name: 'Test' };
const quiet = () => {};

// Raster: 550x357 logo, a coloured shape with 60px transparent margins.
const root = mkdtempSync(path.join(tmpdir(), 'site-kit-favicon-'));
mkdirSync(path.join(root, 'public'));
mkdirSync(path.join(root, 'src/assets'), { recursive: true });
const shape = await sharp({ create: { width: 430, height: 237, channels: 4, background: { r: 0, g: 110, b: 180, alpha: 1 } } }).png().toBuffer();
await sharp({ create: { width: 550, height: 357, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
  .composite([{ input: shape, left: 60, top: 60 }])
  .png()
  .toFile(path.join(root, 'src/assets/logo.png'));
await favicon({ root, site, log: quiet });

const icon = await sharp(path.join(root, 'public/icon-512.png')).metadata();
expect('raster: icon-512 is 512×512', icon.width === 512 && icon.height === 512);
const { data } = await sharp(path.join(root, 'public/icon-512.png')).raw().toBuffer({ resolveWithObject: true });
const alphaAt = (x, y) => data[(y * 512 + x) * 4 + 3];
expect('raster: transparent edges trimmed (logo touches the left edge)', alphaAt(0, 256) === 255);
expect('raster: square padding stays transparent (top-left corner)', alphaAt(0, 0) === 0);
const apple = await sharp(path.join(root, 'public/apple-touch-icon.png')).raw().toBuffer({ resolveWithObject: true });
expect('raster: apple-touch-icon is opaque (white corner)', apple.data[3] === 255 && apple.data[0] === 255);
const svg = readFileSync(path.join(root, 'public/favicon.svg'), 'utf8');
expect('raster: favicon.svg wraps the PNG and is marked generated', svg.includes('generated by site-kit favicon') && svg.includes('data:image/png;base64,'));
await favicon({ root, site, log: quiet });
expect('raster: a second run still uses the PNG, not its own favicon.svg', readFileSync(path.join(root, 'public/favicon.svg'), 'utf8') === svg);
const ico = readFileSync(path.join(root, 'public/favicon.ico'));
expect('raster: favicon.ico has 2 images', ico.readUInt16LE(2) === 1 && ico.readUInt16LE(4) === 2);

// SVG source wins over logo.png when it is hand-made.
writeFileSync(path.join(root, 'public/favicon.svg'), '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" fill="oklch(62.8% 0.2577 29.23)"/></svg>');
await favicon({ root, site, log: quiet });
const red = await sharp(path.join(root, 'public/icon-192.png')).raw().toBuffer();
expect('svg: hand-made favicon.svg is the source, OKLCH red renders red', red[0] === 255 && red[1] === 0 && red[2] === 0);

rmSync(root, { recursive: true, force: true });
process.exit(results.every(Boolean) ? 0 : 1);
