// Files generated from the built HTML plus site data: sitemap.xml, robots.txt, llms.txt,
// .htaccess (security headers incl. a hash-based CSP) and the IndexNow key file.
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { parseHTML } from 'linkedom';
import { DAYS, weekdayNames } from './hours.js';

/** All .html files under dir, as paths relative to dir with forward slashes. */
export async function htmlFiles(dir) {
  const entries = await readdir(dir, { recursive: true, withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.html'))
    .map((entry) => path.relative(dir, path.join(entry.parentPath, entry.name)).split(path.sep).join('/'))
    .sort();
}

/** "en/privacy/index.html" -> "/en/privacy/"; "404.html" -> "/404.html" */
export function urlPath(relative) {
  if (relative === 'index.html') return '/';
  if (relative.endsWith('/index.html')) return `/${relative.slice(0, -'index.html'.length)}`;
  return `/${relative}`;
}

/** Read every built page once: url, title, lang, noindex, inline script bodies. */
export async function readPages(dir) {
  const pages = [];
  for (const relative of await htmlFiles(dir)) {
    const html = await readFile(path.join(dir, relative), 'utf8');
    const { document } = parseHTML(html);
    const robots = document.querySelector('meta[name="robots"]')?.getAttribute('content') ?? '';
    pages.push({
      relative,
      path: urlPath(relative),
      html,
      document,
      title: document.querySelector('title')?.textContent?.trim() ?? '',
      lang: document.documentElement.getAttribute('lang') ?? '',
      noindex: /noindex/i.test(robots) || relative === '404.html',
      inlineScripts: [...document.querySelectorAll('script:not([src])')]
        .filter((script) => !/json/i.test(script.getAttribute('type') ?? ''))
        .map((script) => script.textContent ?? ''),
    });
  }
  return pages;
}

const escapeXml = (value) => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

export function buildCsp(site, pages, extra = {}) {
  const hashes = new Set();
  for (const page of pages) {
    for (const body of page.inlineScripts) hashes.add(`'sha256-${createHash('sha256').update(body).digest('base64')}'`);
  }
  const analytics = site.analytics ? new URL(site.analytics.umami.scriptUrl).origin : null;
  const form = site.forms.contact ? new URL(site.forms.contact.endpoint).origin : null;
  const directives = {
    'default-src': ["'self'"],
    'script-src': ["'self'", ...(analytics ? [analytics] : []), ...[...hashes].sort()],
    'connect-src': ["'self'", ...(analytics ? [analytics] : [])],
    'img-src': ["'self'", 'data:'],
    'style-src': ["'self'"],
    'font-src': ["'self'"],
    'form-action': ["'self'", ...(form ? [form] : [])],
    'base-uri': ["'self'"],
    'frame-ancestors': ["'none'"],
    'object-src': ["'none'"],
    ...extra,
  };
  return Object.entries(directives)
    .map(([name, values]) => `${name} ${values.join(' ')}`)
    .join('; ');
}

export function buildHeaders(site, pages) {
  return {
    'Content-Security-Policy': buildCsp(site, pages),
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'X-Content-Type-Options': 'nosniff',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
    ...site.headers,
  };
}

function htaccess(headers) {
  const lines = Object.entries(headers).map(([name, value]) => `  Header always set ${name} "${value.replace(/"/g, '\\"')}"`);
  return [
    '# Generated by @djoek/site-kit. Do not edit: set extra headers in site.config.',
    'AddDefaultCharset utf-8',
    'Options -Indexes',
    'ErrorDocument 404 /404.html',
    '<IfModule mod_headers.c>',
    ...lines,
    '</IfModule>',
    '',
  ].join('\n');
}

/** Parse the headers back out of a generated .htaccess (used by the check server). */
export function parseHtaccessHeaders(text) {
  const headers = {};
  for (const match of text.matchAll(/^\s*Header always set (\S+) "((?:[^"\\]|\\.)*)"\s*$/gm)) {
    headers[match[1]] = match[2].replace(/\\"/g, '"');
  }
  return headers;
}

function formatIntervals(intervals, closed) {
  return intervals.length ? intervals.map(([open, close]) => `${open}–${close}`).join(', ') : closed;
}

function llms(site, copy, hours, pages) {
  const lang = site.defaultLanguage;
  const kit = copy[lang].kit;
  const lines = [`# ${site.name}`, '', `> ${copy[lang].site?.description ?? ''}`, '', '## Pages', ''];
  const ordered = [...pages].sort((a, b) => Number(b.lang === lang) - Number(a.lang === lang));
  for (const page of ordered.filter((p) => !p.noindex)) lines.push(`- [${page.title}](${site.url}${page.path})${page.lang ? ` (${page.lang})` : ''}`);
  lines.push('', '## Contact', '', `- ${kit.address.email}: ${site.email}`);
  if (site.phone) lines.push(`- ${kit.address.phone}: ${site.phone}`);
  if (site.address) {
    const a = site.address;
    lines.push(`- ${a.street}, ${a.postalCode} ${a.locality}, ${a.country}`);
  }
  if (hours) {
    const names = weekdayNames(lang);
    lines.push('', `## ${kit.hours.caption}`, '');
    DAYS.forEach((day, index) => lines.push(`- ${names[index]}: ${formatIntervals(hours.week[day], kit.hours.closed)}`));
    if (hours.exceptions.length) {
      lines.push('', `### ${kit.hours.exceptionsCaption}`, '');
      for (const e of hours.exceptions) {
        const when = e.to ? `${e.date} – ${e.to}` : e.date;
        const note = e.note[lang] ? ` (${e.note[lang]})` : '';
        lines.push(`- ${when}: ${e.closed ? kit.hours.closed : formatIntervals(e.hours, kit.hours.closed)}${note}`);
      }
    }
  }
  return `${lines.join('\n')}\n`;
}

/** Write all generated files into the build directory. Returns the list of written names. */
export async function writeOutputs(dir, { site, copy, hours }) {
  const pages = await readPages(dir);
  const indexable = pages.filter((page) => !page.noindex);
  const files = {
    'sitemap.xml': [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
      ...indexable.map((page) => `  <url><loc>${escapeXml(site.url + page.path)}</loc></url>`),
      '</urlset>',
      '',
    ].join('\n'),
    'robots.txt': `User-agent: *\nAllow: /\n\nSitemap: ${site.url}/sitemap.xml\n`,
    'llms.txt': llms(site, copy, hours, pages),
    '.htaccess': htaccess(buildHeaders(site, pages)),
  };
  if (site.indexNowKey) files[`${site.indexNowKey}.txt`] = site.indexNowKey;
  for (const [name, content] of Object.entries(files)) await writeFile(path.join(dir, name), content);
  return Object.keys(files);
}
